//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.TanentApplication = new HashSet<TanentApplication>();
            this.TanentRent = new HashSet<TanentRent>();
            this.Unit = new HashSet<Unit>();
        }
    
        public int ID { get; set; }
        public string ClientName { get; set; }
        public string Occupation { get; set; }
        public string HomeAddress { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Type { get; set; }
        public string PostalCode { get; set; }
        public string Work_DayTime_Phone { get; set; }
        public string Home_Evening_Phone { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<TanentApplication> TanentApplication { get; set; }
        public virtual ICollection<TanentRent> TanentRent { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
    }
}
