//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Owner_Currency = new HashSet<Owner_Currency>();
        }
    
        public int ID { get; set; }
        public string Currency1 { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Owner_Currency> Owner_Currency { get; set; }
    }
}
