//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricalAppliance
    {
        public ElectricalAppliance()
        {
            this.Unit_ElectricalAppliance = new HashSet<Unit_ElectricalAppliance>();
        }
    
        public int ID { get; set; }
        public string ElectricalApplianceName { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Unit_ElectricalAppliance> Unit_ElectricalAppliance { get; set; }
    }
}
