//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerRent
    {
        public int ID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> Rate { get; set; }
        public string RefNumber { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> CR { get; set; }
        public Nullable<double> DB { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
